Formatting

diff --git a/bin/deploy-websocket b/bin/deploy-websocket
--- a/bin/deploy-websocket
+++ b/bin/deploy-websocket
@@ -33,13 +33,13 @@ assert_var description "Argument 3: DESCRIPTION is not set"
 log "Creating deployment on API Websocket Gateway"
 
 response="$(aws apigatewayv2 create-deployment --stage-name "$matrix" --description "$description-$matrix" --api-id "$api_gateway_ws_id")"
-deployment_status=$(jq -r '.DeploymentStatus' <<< "$response" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
+deployment_status=$(jq -r '.DeploymentStatus' <<<"$response" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
 
 # Check if deployment status is "FAILED"
 if [ "$deployment_status" = "FAILED" ]; then
-    log "Failed to create deploy on API Websocket Gateway"
-    log "Error: "
-    log "$response"
-    exit 1
+	log "Failed to create deploy on API Websocket Gateway"
+	log "Error: "
+	log "$response"
+	exit 1
 fi
 log "Created deployment on API Websocket Gateway"
